# This workflow will run the three lint tools
name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install ESLint Formatter
        run: |
          npm install @microsoft/eslint-formatter-sarif
          
      - name: Lint JavaScript
        if: ${{ ! cancelled() }}
        run: npm run eslint
  
      - name: Lint HTML
        if: ${{ ! cancelled() }}
        run: npm run htmllint
  
      - name: Lint CSS
        if: ${{ ! cancelled() }}
        run: npm run csslint
        
      - name: Run linters
        if: ${{ ! cancelled() }}
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          stylelint: true
